version: "3.8"
services:
  database:
    image: postgres
    container_name: rentx_database
    restart: unless-stopped
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres
    network_mode: "host"
  app:
    depends_on:
      - "database"
    build: .
    container_name: rentx
    volumes:
      - .:/usr/app
    network_mode: "host"
volumes:
  pgdata:
    driver: local
